'use strict';

const FLOW_STEPS = { layout: 1, cost: 2, brief: 3, review: 4 };
let currentAppView = 'home';
let currentJobVariants = [];
let selectedHomeService = 'laser';
let selectedJobType = '';
let jobNickname = '';
let costPreviewMode = 'sheet';
let costPiecePaperRotation = 0;
let lockedCuttingMode = '';
let pendingVariantQuantityChange = null;
let quickBriefMode = false;

const JOB_TYPE_DEFAULTS = {
  'งานกระดาษ': { width: 9, height: 5.4, quantity: 500, preset: /13\s*[×x*]?\s*19.*manual|manual.*13\s*[×x*]?\s*19/i, cutting: '' },
  'สติกเกอร์ Die-cut 50%': { width: 6, height: 6, quantity: 100, preset: /13\s*[×x*]?\s*19.*mimaki|mimaki.*13\s*[×x*]?\s*19/i, cutting: '50' },
  'สติกเกอร์ Die-cut 100%': { width: 6, height: 6, quantity: 100, preset: /13\s*[×x*]?\s*19.*flatblade|flatblade.*13\s*[×x*]?\s*19/i, cutting: '100' }
};

const JOB_NAME_SUFFIXES = [
  'ชุดใหม่',
  'ล็อตเดือนนี้',
  'เวอร์ชันอัปเดต',
  'สำหรับโปรเจกต์ล่าสุด',
  'รอบผลิตใหม่'
];

function isJobNameSuggestionVisible(suggestion, jobType = selectedJobType) {
  const stickerJob = /สติกเกอร์|sticker/i.test(String(jobType || ''));
  const paperJob = String(jobType || '').trim() === 'งานกระดาษ';
  const stickerSuggestion = /สติกเกอร์|sticker/i.test(String(suggestion || ''));
  if (stickerJob) return stickerSuggestion;
  if (paperJob) return !stickerSuggestion;
  return true;
}

function randomJobNickname(suggestion, randomValue = Math.random()) {
  const normalized = Math.max(0, Math.min(0.999999, Number(randomValue) || 0));
  const suffix = JOB_NAME_SUFFIXES[Math.floor(normalized * JOB_NAME_SUFFIXES.length)];
  return `${String(suggestion || '').trim()} ${suffix}`.trim();
}

function syncJobNameSuggestions() {
  document.querySelectorAll('[data-job-name-suggestion]').forEach(button => {
    const visible = isJobNameSuggestionVisible(button.dataset.jobNameSuggestion, selectedJobType);
    button.hidden = !visible;
    button.setAttribute('aria-hidden', visible ? 'false' : 'true');
    if (!visible) {
      button.classList.remove('is-selected');
      button.setAttribute('aria-pressed', 'false');
    }
  });
}

function flowEscape(value) {
  return String(value || '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function generatedJobName(type, nickname = jobNickname) {
  const customName = String(nickname || '').trim();
  if (customName) return customName;
  const normalizedType = String(type || 'งานพิมพ์').trim();
  const width = Number($('w')?.value) || 0;
  const height = Number($('h')?.value) || 0;
  const date = new Date().toLocaleDateString('th-TH-u-ca-gregory', { day: '2-digit', month: '2-digit', year: 'numeric' });
  return `${normalizedType} • ${width}×${height} cm • ${date}`;
}

function setJobType(type, options = {}) {
  const previousJobType = selectedJobType;
  selectedJobType = String(type || '').trim();
  lockedCuttingMode = JOB_TYPE_DEFAULTS[selectedJobType]?.cutting || '';
  if (previousJobType !== selectedJobType && typeof resetCuttingDefaultSelection === 'function') resetCuttingDefaultSelection();
  document.querySelectorAll('[data-job-type]').forEach(button => {
    const selected = button.dataset.jobType === selectedJobType;
    button.classList.toggle('is-selected', selected);
    button.setAttribute('aria-pressed', selected ? 'true' : 'false');
  });
  syncJobNameSuggestions();
  const input = $('jobName');
  if (!input || options.preserveName) return;
  const name = generatedJobName(selectedJobType, jobNickname);
  input.value = name;
  input.dataset.autoGenerated = name;
  input.classList.remove('is-invalid');
  announceUiChange(`สร้างชื่อเรียกงาน “${name}” แล้ว`, input, { scroll: false });
}

function setJobNickname(value, options = {}) {
  jobNickname = String(value || '').trim();
  if ($('jobNickname')) $('jobNickname').value = jobNickname;
  if (!options.preserveName && $('jobName')) {
    const name = generatedJobName(selectedJobType, jobNickname);
    $('jobName').value = name;
    $('jobName').dataset.autoGenerated = name;
  }
}

function showJobSetupQuestion(step = 1) {
  const activeStep = Math.max(1, Math.min(3, Number(step) || 1));
  document.querySelector('.job-quiz-shell')?.classList.toggle('is-question-2', activeStep === 2);
  document.querySelectorAll('[data-job-quiz-question]').forEach(panel => {
    const active = Number(panel.dataset.jobQuizQuestion) === activeStep;
    panel.classList.toggle('is-active', active);
    panel.setAttribute('aria-hidden', active ? 'false' : 'true');
  });
  document.querySelectorAll('[data-job-quiz-step]').forEach(marker => marker.classList.toggle('is-active', Number(marker.dataset.jobQuizStep) <= activeStep));
  requestAnimationFrame(() => document.querySelector(`[data-job-quiz-question="${activeStep}"] h1`)?.focus({ preventScroll: true }));
}

function completeJobSetup() {
  syncQuizBriefInputs();
  const recommendation = applyJobTypeDefaults();
  if (!recommendation) {
    const variants = getJobVariants();
    if (variants.length === 1 && !variants[0].name) setJobVariants([{ ...variants[0], name: jobNickname || 'แบบหลัก' }]);
  }
  const name = generatedJobName(selectedJobType, jobNickname);
  $('jobName').value = name;
  $('jobName').dataset.autoGenerated = name;
  showAppView('layout');
  if (recommendation) announceUiChange(`ตั้งค่าแนะนำแล้ว: ${recommendation}`, $('previewDropZone'), { scroll: false });
  else announceUiChange('เข้าสู่โหมด Manual คุณสามารถตั้งค่าชิ้นงานได้ตามต้องการ');
}

function syncQuizBriefInputs() {
  setJobNickname($('jobNickname')?.value || '');
  const briefDate = getLocalTodayIso();
  const deliveryDate = normalizeFlowDateValue($('quizDeliveryDeadline')?.value);
  if ($('briefDeadline')) $('briefDeadline').value = formatFlowDateInput(briefDate);
  if ($('deliveryDeadline')) $('deliveryDeadline').value = formatFlowDateInput(deliveryDate);
  const briefNative = document.querySelector('[data-date-for="briefDeadline"]');
  const deliveryNative = document.querySelector('[data-date-for="deliveryDeadline"]');
  if (briefNative) briefNative.value = briefDate;
  if (deliveryNative) deliveryNative.value = deliveryDate;
}

function hydrateQuizFromBrief() {
  setQuizDateValue('quizDeliveryDeadline', normalizeFlowDateValue($('deliveryDeadline')?.value));
}

function getSelectedJobType() {
  return selectedJobType;
}

function applyJobTypeDefaults() {
  const defaults = JOB_TYPE_DEFAULTS[selectedJobType];
  lockedCuttingMode = defaults?.cutting || '';
  if (!defaults) {
    if (typeof renderServices === 'function') renderServices();
    return '';
  }
  $('w').value = defaults.width;
  $('h').value = defaults.height;
  $('qty').value = defaults.quantity;
  setJobVariants([{ name: jobNickname || (selectedJobType === 'อื่น ๆ' ? 'แบบหลัก' : selectedJobType), quantity: defaults.quantity }]);
  const presetEntry = Object.entries(presets || {}).find(([, preset]) => defaults.preset.test(String(preset?.name || '')));
  if (presetEntry) {
    selectedSheet = presetEntry[0];
    $('sheet').value = selectedSheet;
    saveState();
  }
  if (typeof renderServices === 'function') renderServices();
  const presetName = presetEntry?.[1]?.name || presets?.[selectedSheet]?.name || 'Preset ปัจจุบัน';
  return `${selectedJobType} • ${defaults.width}×${defaults.height} cm • ${defaults.quantity.toLocaleString('th-TH')} ชิ้น • ${presetName}`;
}

function showAppView(name, options = {}) {
  const target = document.querySelector(`[data-app-view="${name}"]`);
  if (!target) return false;
  const previousView = currentAppView;

  document.querySelectorAll('[data-app-view]').forEach(view => {
    const active = view === target;
    view.classList.toggle('is-active', active);
    if (!active) view.classList.remove('open');
    view.setAttribute('aria-hidden', active ? 'false' : 'true');
  });

  currentAppView = name;
  if (name === 'jobSetup' && previousView !== 'home') hydrateQuizFromBrief();
  updateFlowStepper(name);
  if ((name === 'layout' || name === 'brief') && typeof setActiveArtworkSide === 'function') setActiveArtworkSide('front');
  if (name === 'layout' && typeof calculate === 'function') {
    requestAnimationFrame(() => calculate());
  }
  if (name === 'quickBrief' && typeof calculate === 'function') {
    requestAnimationFrame(() => { calculate(); syncQuickBriefSummary(); });
  }
  if (name === 'cost' || name === 'brief' || name === 'review') syncFlowSummary();
  if (name === 'cart' && typeof renderCart === 'function') renderCart();
  if (!options.preserveScroll) window.scrollTo({ top: 0, behavior: options.instant ? 'auto' : 'smooth' });
  return true;
}

function updateFlowStepper(view) {
  const stepper = $('flowStepper');
  const step = FLOW_STEPS[view] || 0;
  stepper.hidden = !step;
  stepper.querySelectorAll('.flow-step').forEach(node => {
    const number = Number(node.dataset.step);
    node.classList.toggle('is-active', number === step);
    node.classList.toggle('is-done', number < step);
  });
}

function miniLayoutMarkup(maximum = 9, side = 'front') {
  const count = Math.max(1, Math.min(maximum, Number(lastCalc?.b?.yield) || 9));
  const artwork = typeof getArtworkPreviewUrl === 'function' ? getArtworkPreviewUrl(side) : '';
  const rotation = typeof getArtworkPlacementRotation === 'function'
    ? getArtworkPlacementRotation(side, Boolean(lastCalc?.b?.rotate))
    : (typeof getArtworkRotation === 'function' ? getArtworkRotation(side) : 0);
  const box = typeof artworkRotationBox === 'function'
    ? artworkRotationBox(rotation, lastCalc?.b?.pieceW, lastCalc?.b?.pieceH)
    : { width: 100, height: 100 };
  return Array.from({ length: count }, () =>
    `<span>${artwork ? `<i class="mini-artwork" style="background-image:url('${flowEscape(artwork)}');--artwork-rotation:${rotation}deg;--artwork-box-width:${box.width}%;--artwork-box-height:${box.height}%"></i>` : ''}</span>`
  ).join('');
}

function flowPreviewMaterialClass() {
  const materialName = String(lastCalc?.material?.name || '').toLowerCase();
  if (/kraft|คราฟท์/.test(materialName)) return 'is-kraft';
  if (/pvc|pp|sticker|สติกเกอร์/.test(materialName)) return 'is-sticker';
  if (/art|อาร์ท/.test(materialName)) return 'is-art-paper';
  return '';
}

function flowPreviewHasDiecut() {
  return (lastCalc?.services || []).some(service => /ไดคัท|die.?cut/.test(String(service?.name || '').toLowerCase()));
}

function flowPreviewHasRoundedCorner() {
  return (lastCalc?.services || []).some(service => /ตัดมุม|rounded.?corner/.test(String(service?.name || '').toLowerCase()));
}

function previewArtworkMarkup(side, width, height) {
  const artwork = typeof getArtworkPreviewUrl === 'function' ? getArtworkPreviewUrl(side) : '';
  if (!artwork) return '<span class="preview-gallery-empty">ยังไม่มีภาพ</span>';
  const rotation = typeof getArtworkPlacementRotation === 'function'
    ? getArtworkPlacementRotation(side, Boolean(lastCalc?.b?.rotate))
    : (typeof getArtworkRotation === 'function' ? getArtworkRotation(side) : 0);
  const box = typeof artworkRotationBox === 'function' ? artworkRotationBox(rotation, width, height) : { width: 100, height: 100 };
  return `<img class="preview-gallery-artwork" data-preview-side="${side}" src="${flowEscape(artwork)}" alt="ภาพงาน${side === 'back' ? 'ด้านหลัง' : 'ด้านหน้า'}" style="--artwork-rotation:${rotation}deg;--artwork-box-width:${box.width}%;--artwork-box-height:${box.height}%">`;
}

function previewGalleryPieceMarkup(side, width, height) {
  const materialClass = flowPreviewMaterialClass();
  const diecutClass = flowPreviewHasDiecut() ? ' has-diecut-effect' : '';
  const cornerClass = flowPreviewHasRoundedCorner() ? ' has-rounded-corner' : '';
  return `<span class="preview-gallery-piece${diecutClass}${cornerClass}">${previewArtworkMarkup(side, width, height)}${materialClass ? `<i class="piece-material-effect ${materialClass}" aria-hidden="true"></i>` : ''}</span>`;
}

function imposedPieceDimensions() {
  return {
    width: Math.max(.05, Number(lastCalc?.b?.pieceW) || Number(lastCalc?.W) * 10 || 1),
    height: Math.max(.05, Number(lastCalc?.b?.pieceH) || Number(lastCalc?.H) * 10 || 1)
  };
}

function previewGallerySurfaceAttributes() {
  const enabled = typeof getMaterialPreviewEnabled !== 'function' || getMaterialPreviewEnabled();
  const config = enabled && typeof materialPreviewConfig === 'function' ? materialPreviewConfig(lastCalc) : { mode: 'none', effect: 'none' };
  return `data-preview-renderer="${flowEscape(config.mode)}" data-preview-effect="${flowEscape(config.effect)}"`;
}

function sheetPreviewGalleryMarkup(side = 'front') {
  if (!lastCalc) return '';
  const paper = lastCalc.paper || {};
  const fullW = Math.max(1, Number(paper.fullW) * 10 || 1);
  const fullH = Math.max(1, Number(paper.fullH) * 10 || 1);
  const usableW = Math.max(1, Math.min(fullW, Number(paper.usableW) * 10 || fullW));
  const usableH = Math.max(1, Math.min(fullH, Number(paper.usableH) * 10 || fullH));
  const nx = Math.max(1, Number(lastCalc.b?.nx) || 1);
  const ny = Math.max(1, Number(lastCalc.b?.ny) || 1);
  const pieceW = Math.max(1, Number(lastCalc.b?.pieceW) || 1);
  const pieceH = Math.max(1, Number(lastCalc.b?.pieceH) || 1);
  const gap = Math.max(0, Number(lastCalc.gap) || 0);
  const gridW = nx * pieceW + Math.max(0, nx - 1) * gap;
  const gridH = ny * pieceH + Math.max(0, ny - 1) * gap;
  const count = Math.max(1, Number(lastCalc.b?.yield) || nx * ny);
  const pieces = Array.from({ length: count }, () => previewGalleryPieceMarkup(side, pieceW, pieceH)).join('');
  const usableStyle = `left:${(fullW - usableW) / fullW * 50}%;top:${(fullH - usableH) / fullH * 50}%;width:${usableW / fullW * 100}%;height:${usableH / fullH * 100}%`;
  const gridStyle = `left:${Math.max(0, (usableW - gridW) / usableW * 50)}%;top:${Math.max(0, (usableH - gridH) / usableH * 50)}%;width:${Math.min(100, gridW / usableW * 100)}%;height:${Math.min(100, gridH / usableH * 100)}%;grid-template-columns:repeat(${nx},1fr);grid-template-rows:repeat(${ny},1fr);column-gap:${gap / usableW * 100}%;row-gap:${gap / usableH * 100}%`;
  return `<div class="preview-gallery-surface preview-gallery-sheet" ${previewGallerySurfaceAttributes()} style="aspect-ratio:${fullW}/${fullH}"><div class="preview-gallery-usable" style="${usableStyle}"><div class="preview-gallery-grid" style="${gridStyle}">${pieces}</div></div><i class="preview-gallery-reflection" aria-hidden="true"></i></div>`;
}

function piecePreviewGalleryMarkup(side = 'front') {
  if (!lastCalc) return '';
  const { width, height } = imposedPieceDimensions();
  const maxWidth = 320;
  const maxHeight = 300;
  const displayScale = Math.min(maxWidth / width, maxHeight / height);
  const displayWidth = Math.max(72, width * displayScale);
  const roundedClass = flowPreviewHasRoundedCorner() ? ' has-rounded-corner' : '';
  return `<div class="preview-gallery-surface preview-gallery-piece-frame${roundedClass}" ${previewGallerySurfaceAttributes()} style="width:${displayWidth}px;aspect-ratio:${width}/${height}">${previewGalleryPieceMarkup(side, width, height)}<i class="preview-gallery-reflection" aria-hidden="true"></i></div>`;
}

function previewGalleryMarkup() {
  const doubleSided = typeof getSelectedPrintSide === 'function' && getSelectedPrintSide() === 'double';
  const hasBackArtwork = typeof getArtworkPreviewUrl === 'function' && Boolean(getArtworkPreviewUrl('back'));
  const sides = doubleSided && hasBackArtwork ? ['front', 'back'] : ['front'];
  const sideLabel = side => side === 'back' ? 'ด้านหลัง' : 'ด้านหน้า';
  const definitions = [
    { kind: 'รายแผ่น', renderer: sheetPreviewGalleryMarkup },
    { kind: 'รายชิ้น', renderer: piecePreviewGalleryMarkup }
  ];
  const slides = definitions.flatMap(({ kind, renderer }) => sides.map(side => ({ kind, side, renderer })));
  const slideMarkup = slides.map((slide, index) => `<article class="preview-gallery-card preview-carousel-slide${index === 0 ? ' is-active' : ''}" data-preview-carousel-slide data-preview-kind="${slide.kind}" data-preview-side="${slide.side}" aria-hidden="${index === 0 ? 'false' : 'true'}"${index === 0 ? '' : ' hidden'}><strong>Preview ${slide.kind} • ${sideLabel(slide.side)}</strong>${slide.renderer(slide.side)}</article>`).join('');
  const dots = slides.map((slide, index) => `<button type="button" data-preview-carousel-index="${index}" class="${index === 0 ? 'is-selected' : ''}" aria-label="ดู Preview ${slide.kind} ${sideLabel(slide.side)}" aria-pressed="${index === 0 ? 'true' : 'false'}"></button>`).join('');
  return `<section class="preview-carousel" data-preview-carousel data-preview-index="0"><div class="preview-carousel-viewport">${slideMarkup}</div><div class="preview-carousel-controls"><button type="button" data-preview-carousel-action="prev" aria-label="ดู Preview ก่อนหน้า">‹</button><div class="preview-carousel-dots">${dots}</div><output data-preview-carousel-status>1 / ${slides.length}</output><button type="button" data-preview-carousel-action="next" aria-label="ดู Preview ถัดไป">›</button></div></section>`;
}

function syncPreviewCarousel(carousel, requestedIndex) {
  const slides = [...carousel.querySelectorAll('[data-preview-carousel-slide]')];
  if (!slides.length) return;
  const index = ((Number(requestedIndex) || 0) % slides.length + slides.length) % slides.length;
  carousel.dataset.previewIndex = String(index);
  slides.forEach((slide, slideIndex) => {
    const selected = slideIndex === index;
    slide.hidden = !selected;
    slide.classList.toggle('is-active', selected);
    slide.setAttribute('aria-hidden', selected ? 'false' : 'true');
  });
  carousel.querySelectorAll('[data-preview-carousel-index]').forEach(button => {
    const selected = Number(button.dataset.previewCarouselIndex) === index;
    button.classList.toggle('is-selected', selected);
    button.setAttribute('aria-pressed', selected ? 'true' : 'false');
  });
  const status = carousel.querySelector('[data-preview-carousel-status]');
  if (status) status.textContent = `${index + 1} / ${slides.length}`;
  carousel.querySelectorAll('[data-preview-carousel-action]').forEach(button => { button.disabled = slides.length < 2; });
}

function renderCostPreviewMode() {
  if (!lastCalc) return;
  const source = $('sheetPreview');
  const preview = $('costSheetPreview');
  const stage = $('materialPreviewStage');
  if (!source || !preview || !stage) return;
  preview.classList.toggle('is-piece-preview', costPreviewMode === 'piece');
  stage.dataset.previewKind = costPreviewMode;
  const pieceTools = $('costPieceTools');
  const rotatePaperButton = $('rotateCostPiecePaper');
  const rotationOutput = $('costPiecePaperRotation');
  if (pieceTools) pieceTools.hidden = costPreviewMode !== 'piece';
  if (rotatePaperButton) rotatePaperButton.setAttribute('aria-label', `หมุนหน้ากระดาษ Preview รายชิ้น 90 องศา มุมปัจจุบัน ${costPiecePaperRotation} องศา`);
  if (rotationOutput) rotationOutput.textContent = `มุมหน้ากระดาษ ${costPiecePaperRotation}°`;
  if (costPreviewMode === 'piece') {
    const sourcePiece = source.querySelector('.piece');
    const piece = sourcePiece ? sourcePiece.cloneNode(true) : document.createElement('div');
    piece.classList.add('piece', 'cost-single-piece');
    piece.removeAttribute('tabindex');
    piece.removeAttribute('role');
    piece.removeAttribute('aria-label');
    piece.querySelector('.piece-number')?.remove();
    const { width: pieceWidth, height: pieceHeight } = imposedPieceDimensions();
    syncPieceMarginLine(piece, pieceWidth, pieceHeight);
    const swapsSides = costPiecePaperRotation % 180 !== 0;
    const viewWidth = swapsSides ? pieceHeight : pieceWidth;
    const viewHeight = swapsSides ? pieceWidth : pieceHeight;
    const available = Math.max(220, Math.min(380, ($('materialPreviewInteraction')?.clientWidth || 360) - 24));
    const ratio = Math.max(.05, viewWidth / Math.max(.05, viewHeight));
    let width = available;
    let height = width / ratio;
    if (height > 360) { height = 360; width = height * ratio; }
    preview.replaceChildren(piece);
    preview.classList.toggle('has-rounded-preview', flowPreviewHasRoundedCorner());
    preview.style.width = `${Math.max(1, width)}px`;
    preview.style.height = `${Math.max(1, height)}px`;
    preview.style.setProperty('--piece-paper-width', `${Math.max(1, swapsSides ? height : width)}px`);
    preview.style.setProperty('--piece-paper-height', `${Math.max(1, swapsSides ? width : height)}px`);
    preview.style.setProperty('--piece-paper-rotation', `${costPiecePaperRotation}deg`);
    preview.classList.toggle('has-paper-rotation', costPiecePaperRotation !== 0);
    stage.dataset.paperRotation = String(costPiecePaperRotation);
  } else {
    preview.classList.remove('has-rounded-preview');
    preview.classList.remove('has-paper-rotation');
    preview.style.removeProperty('--piece-paper-width');
    preview.style.removeProperty('--piece-paper-height');
    preview.style.removeProperty('--piece-paper-rotation');
    delete stage.dataset.paperRotation;
    preview.innerHTML = source.innerHTML;
    preview.style.width = source.style.width;
    preview.style.height = source.style.height;
  }
  document.querySelectorAll('[data-cost-preview-mode]').forEach(button => {
    const selected = button.dataset.costPreviewMode === costPreviewMode;
    button.classList.toggle('is-selected', selected);
    button.setAttribute('aria-pressed', selected ? 'true' : 'false');
  });
  if (typeof syncMaterialPreviewEffect === 'function') syncMaterialPreviewEffect(lastCalc);
}

function setCostPreviewMode(mode) {
  const previousMode = costPreviewMode;
  costPreviewMode = mode === 'piece' ? 'piece' : 'sheet';
  renderCostPreviewMode();
  if (previousMode !== costPreviewMode) {
    if (costPreviewMode === 'piece') announceUiChange('เปิดเครื่องมือ Preview รายชิ้นแล้ว', $('costPieceTools'));
    else announceUiChange('เปลี่ยนเป็น Preview รายแผ่นแล้ว', $('costSheetPreview'));
  }
}

function getCostPreviewMode() {
  return costPreviewMode;
}

function rotateCostPiecePaper() {
  if (costPreviewMode !== 'piece') return false;
  costPiecePaperRotation = (costPiecePaperRotation + 90) % 360;
  renderCostPreviewMode();
  return true;
}

function getCostPiecePaperRotation() {
  return costPiecePaperRotation;
}

function syncFlowSummary() {
  if (!lastCalc) return;
  const layout = `${lastCalc.b.nx} × ${lastCalc.b.ny} (${lastCalc.b.rotate ? 'หมุน 90°' : 'แนวปกติ'})`;
  const source = $('sheetPreview');
  const costPreview = $('costSheetPreview');

  if ($('layoutDirection')) $('layoutDirection').textContent = layout;
  if ($('sheetWidthLabel')) $('sheetWidthLabel').textContent = `${Number(lastCalc.paper.fullW * 10).toLocaleString('th-TH')} mm`;
  if ($('sheetHeightLabel')) $('sheetHeightLabel').textContent = `${Number(lastCalc.paper.fullH * 10).toLocaleString('th-TH')} mm`;
  if ($('costLayoutSummary')) $('costLayoutSummary').textContent = `${lastCalc.b.yield} ชิ้น/แผ่น (ใช้ ${lastCalc.sheets} แผ่น)`;
  if ($('briefCalcSummary')) {
    $('briefCalcSummary').innerHTML = `ขนาด ${Number(lastCalc.W).toLocaleString('th-TH')}×${Number(lastCalc.H).toLocaleString('th-TH')} cm • ${Number(lastCalc.Q).toLocaleString('th-TH')} ชิ้น<br>• ${lastCalc.b.yield} ชิ้น / แผ่น รวม ${lastCalc.sheets} แผ่น`;
  }
  if ($('briefArtworkPreview')) $('briefArtworkPreview').innerHTML = previewGalleryMarkup();
  if ($('previewFinishStatus')) {
    const finishNames = [lastCalc.material?.name, ...(lastCalc.services || []).map(service => service.name)].filter(Boolean);
    const rendererEnabled = typeof getMaterialPreviewEnabled !== 'function' || getMaterialPreviewEnabled();
    const renderer = rendererEnabled && typeof materialPreviewConfig === 'function' ? materialPreviewConfig(lastCalc) : { mode: 'none' };
    const rendererLabel = renderer.mode === 'webgl' ? ' • WebGL 2.5D' : renderer.mode === 'css' ? ' • CSS 2.5D' : '';
    $('previewFinishStatus').textContent = finishNames.length
      ? `Preview: ${finishNames.join(' • ')}${rendererLabel}`
      : 'Preview วัสดุและ Option เสริม';
  }
  if ($('costPrintSummary')) {
    const printService = (lastCalc.services || []).find(service => typeof isPrintSideService === 'function' && isPrintSideService(service));
    const side = typeof getSelectedPrintSide === 'function' ? getSelectedPrintSide() : 'unspecified';
    $('costPrintSummary').textContent = printService?.name || (side === 'double' ? 'พิมพ์หน้า–หลัง' : side === 'single' ? 'พิมพ์หน้าเดียว' : 'ยังไม่ได้เลือกรูปแบบการพิมพ์');
    if ($('costPrintPrice')) $('costPrintPrice').textContent = `฿${money(printService ? quantityServicePrice(printService, lastCalc) : 0)}`;
  }
  if ($('costSelectedServices')) {
    const selectedServices = Array.isArray(lastCalc.services) ? lastCalc.services : [];
    $('costSelectedServices').innerHTML = selectedServices.length
      ? selectedServices.map(service => `<span><b>${flowEscape(service.name || 'บริการเพิ่มเติม')}</b><strong>${servicePriceLabel(service, lastCalc)}</strong></span>`).join('')
      : '<span><b>ไม่มีบริการเพิ่มเติม</b><strong>฿0.00</strong></span>';
  }
  syncQuickBriefSummary();

  if (source && costPreview) renderCostPreviewMode();
  if (typeof syncArtworkSideControls === 'function') syncArtworkSideControls();
}

function syncQuickBriefControls() {
  if (!$('quickSheet')) return;
  $('quickSheet').value = selectedSheet || '';
  $('quickMaterialSelect').value = selectedMaterialId || '';
  $('quickW').value = $('w')?.value || '9';
  $('quickH').value = $('h')?.value || '5.4';
  $('quickQty').value = $('qty')?.value || '500';
  $('quickJobName').value = $('jobName')?.value || '';
}

function syncQuickBriefSummary() {
  if (!$('quickSheetPreview')) return;
  const source = $('sheetPreview');
  const preview = $('quickSheetPreview');
  if (source) {
    preview.innerHTML = source.innerHTML;
    preview.style.cssText = source.style.cssText;
  }
  if (!lastCalc) {
    $('quickYield').textContent = '—';
    $('quickSheets').textContent = '—';
    $('quickSale').textContent = '—';
    return;
  }
  $('quickYield').textContent = Number(lastCalc.b.yield).toLocaleString('th-TH');
  $('quickSheets').textContent = Number(lastCalc.sheets).toLocaleString('th-TH');
  $('quickSale').textContent = money(lastCalc.sale);
  const selectedServices = Array.isArray(lastCalc.services) ? lastCalc.services : [];
  $('quickSelectedServices').innerHTML = selectedServices.length
    ? selectedServices.map(service => `<span><b>${flowEscape(service.name || 'บริการเพิ่มเติม')}</b><strong>${servicePriceLabel(service, lastCalc)}</strong></span>`).join('')
    : '<span><b>ไม่มีบริการเพิ่มเติม</b><strong>฿0.00</strong></span>';
}

function startQuickBrief() {
  prepareNewPrintItem();
  quickBriefMode = true;
  selectedMaterialId = '';
  selectedServiceIds = {};
  customServiceRequest = '';
  setJobType('ตั้งค่า Manual', { preserveName: true });
  saveState();
  if (typeof renderMaterials === 'function') renderMaterials();
  if (typeof renderServices === 'function') renderServices();
  syncQuickBriefControls();
  if ($('quickDeliveryDeadline')) $('quickDeliveryDeadline').value = '';
  const quickDeliveryPicker = document.querySelector('[data-date-for="quickDeliveryDeadline"]');
  if (quickDeliveryPicker) quickDeliveryPicker.value = '';
  if ($('quickBriefFileLink')) $('quickBriefFileLink').value = '';
  if ($('quickBriefDescription')) $('quickBriefDescription').value = '';
  if ($('quickBriefStatus')) $('quickBriefStatus').textContent = '';
  calculate();
  showAppView('quickBrief');
}

function focusQuickBriefField(field, message) {
  if ($('quickBriefStatus')) $('quickBriefStatus').textContent = message;
  if (!field) return;
  field.setAttribute('aria-invalid', 'true');
  field.closest('.form-card')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  window.setTimeout(() => field.focus({ preventScroll: true }), 250);
}

function continueQuickBrief() {
  const name = $('quickJobName')?.value.trim() || 'งานพิมพ์ Quick Brief';
  const deliveryDate = normalizeFlowDateValue($('quickDeliveryDeadline')?.value);
  const sourceFileLink = $('quickBriefFileLink')?.value.trim() || '';
  const today = getLocalTodayIso();
  if (!lastCalc) {
    focusQuickBriefField($('quickSheet'), 'กรุณาตรวจสอบขนาด จำนวน และ Preset กระดาษ');
    return;
  }
  if (!validateCustomServiceRequest('quick')) return;
  if (!deliveryDate || deliveryDate < today) {
    focusQuickBriefField($('quickDeliveryDeadline'), 'กรุณาเลือกวันที่ต้องการรับงานตั้งแต่วันนี้เป็นต้นไป');
    return;
  }
  let validSourceFileLink = false;
  try {
    const parsedSourceFileLink = new URL(sourceFileLink);
    validSourceFileLink = ['http:', 'https:'].includes(parsedSourceFileLink.protocol);
  } catch {}
  if (!validSourceFileLink) {
    focusQuickBriefField($('quickBriefFileLink'), 'กรุณาใส่ลิงก์ไฟล์ต้นฉบับที่เปิดให้ทีมงานเข้าถึงได้');
    return;
  }
  [$('quickSheet'), $('quickDeliveryDeadline'), $('quickBriefFileLink')].forEach(field => field?.removeAttribute('aria-invalid'));
  $('jobName').value = name;
  $('jobName').dataset.autoGenerated = name;
  setJobNickname(name, { preserveName: true });
  setJobVariants([{ name, quantity: Number(lastCalc.Q) || 0 }]);
  $('briefDeadline').value = formatFlowDateInput(today);
  $('deliveryDeadline').value = formatFlowDateInput(deliveryDate);
  const briefNative = document.querySelector('[data-date-for="briefDeadline"]');
  const deliveryNative = document.querySelector('[data-date-for="deliveryDeadline"]');
  if (briefNative) briefNative.value = today;
  if (deliveryNative) deliveryNative.value = deliveryDate;
  $('briefFileLink').value = sourceFileLink;
  $('graphicBriefDescription').value = $('quickBriefDescription')?.value.trim() || '';
  syncFlowSummary();
  if (renderBriefReview({ skipValidation: true })) showAppView('review');
}

function variantId() {
  return globalThis.crypto?.randomUUID?.() || `variant-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function normalizeVariants(variants) {
  const source = Array.isArray(variants) && variants.length ? variants : [{ name: '', quantity: Number($('qty')?.value) || 0 }];
  return source.slice(0, 12).map(variant => ({
    id: String(variant.id || variantId()),
    name: String(variant.name || ''),
    quantity: Number(variant.quantity) || 0
  }));
}

function renderJobVariants() {
  const container = $('jobVariants');
  if (!container) return;
  currentJobVariants = normalizeVariants(currentJobVariants);
  container.innerHTML = currentJobVariants.map((variant, index) => `
    <div class="job-variant" data-variant-id="${flowEscape(variant.id)}">
      <strong>แบบที่ ${index + 1}</strong>
      <input data-variant-name maxlength="80" value="${flowEscape(variant.name)}" placeholder="คำตัวอย่าง แบบเวอร์ชั่นภาษาไทย">
      <div class="variant-quantity-field"><input data-variant-quantity type="number" min="1" step="1" value="${variant.quantity || ''}" placeholder="จำนวน" aria-label="จำนวนแบบที่ ${index + 1}"><span>ชิ้น</span></div>
      <button data-remove-variant type="button" aria-label="ลบแบบที่ ${index + 1}"${currentJobVariants.length === 1 ? ' hidden' : ''}>×</button>
    </div>`).join('');
}

function readVariantInputs() {
  return Array.from(document.querySelectorAll('.job-variant')).map(row => ({
    id: row.dataset.variantId || variantId(),
    name: row.querySelector('[data-variant-name]')?.value.trim() || '',
    quantity: Number(row.querySelector('[data-variant-quantity]')?.value) || 0
  }));
}

function getJobVariants() {
  currentJobVariants = readVariantInputs();
  return currentJobVariants.map(variant => ({ ...variant }));
}

function setJobVariants(variants) {
  currentJobVariants = normalizeVariants(variants);
  renderJobVariants();
}

function validateJobVariants(showMessage = true) {
  const variants = getJobVariants();
  const expected = Number($('qty')?.value) || 0;
  const total = variants.reduce((sum, variant) => sum + variant.quantity, 0);
  const status = $('variantStatus');
  let message = '';

  if (!variants.length) message = 'กรุณาเพิ่มอย่างน้อย 1 แบบ';
  else if (variants.some(variant => variant.quantity <= 0)) message = 'กรุณาระบุจำนวนของทุกแบบ';
  else if (total !== expected) message = `จำนวนทุกแบบรวม ${total.toLocaleString('th-TH')} ชิ้น ต้องเท่ากับจำนวนงาน ${expected.toLocaleString('th-TH')} ชิ้น`;

  if (status && showMessage) {
    status.textContent = message || `รวม ${total.toLocaleString('th-TH')} ชิ้น ถูกต้อง`;
    status.className = `status ${message ? 'warn' : 'ok'}`;
  }
  return !message;
}

function normalizeFlowDateValue(value) {
  const text = String(value || '').trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return text;
  const match = text.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (!match) return '';
  const day = Number(match[1]);
  const month = Number(match[2]);
  const year = Number(match[3]);
  const date = new Date(year, month - 1, day);
  if (date.getFullYear() !== year || date.getMonth() !== month - 1 || date.getDate() !== day) return '';
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function formatFlowDateInput(value) {
  const iso = normalizeFlowDateValue(value);
  if (!iso) return String(value || '');
  const [year, month, day] = iso.split('-');
  return `${day}/${month}/${year}`;
}

function getLocalTodayIso() {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0');
  const day = String(today.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function setQuizDateValue(id, value) {
  const iso = normalizeFlowDateValue(value);
  const display = $(id);
  const picker = document.querySelector(`[data-quiz-date-for="${id}"]`);
  if (display) display.value = iso ? formatFlowDateInput(iso) : '';
  if (picker) picker.value = iso;
}

function formatGregorianDate(value) {
  const iso = normalizeFlowDateValue(value);
  if (!iso) return '-';
  const date = new Date(`${iso}T00:00:00`);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('th-TH-u-ca-gregory', { day: 'numeric', month: 'short', year: 'numeric' });
}

function focusBriefField(element, message, errorId = '') {
  const status = $('briefFormStatus');
  if (status) {
    status.textContent = message;
    status.className = 'brief-form-status status warn';
  }
  if (errorId && $(errorId)) $(errorId).textContent = message;
  element?.classList.add('is-invalid');
  requestAnimationFrame(() => {
    element?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    element?.focus({ preventScroll: true });
  });
  return false;
}

function validateBriefForm() {
  document.querySelectorAll('.is-invalid').forEach(element => element.classList.remove('is-invalid'));
  document.querySelectorAll('.field-error').forEach(element => { element.textContent = ''; });
  if ($('briefFormStatus')) $('briefFormStatus').textContent = '';
  if (!$('jobName').value.trim()) return focusBriefField($('jobName'), 'กรุณากรอกชื่องาน');
  if (!validateJobVariants(true)) {
    const invalidVariant = [...document.querySelectorAll('#jobVariants input')].find(input => {
      if (input.classList.contains('variant-quantity')) return Number(input.value) <= 0;
      return input.classList.contains('variant-name') && !input.value.trim();
    }) || document.querySelector('#jobVariants input');
    return focusBriefField(invalidVariant || $('jobVariants'), 'กรุณาตรวจสอบชื่อและจำนวนของแต่ละแบบ');
  }
  const briefDate = normalizeFlowDateValue($('briefDeadline').value);
  if (!briefDate) return focusBriefField($('briefDeadline'), 'กรุณาระบุวันรับออร์เดอร์', 'briefDeadlineError');
  const deliveryDate = normalizeFlowDateValue($('deliveryDeadline').value);
  if (!deliveryDate) return focusBriefField($('deliveryDeadline'), 'กรุณาระบุวันส่งสินค้า', 'deliveryDeadlineError');
  if (deliveryDate < briefDate) return focusBriefField($('deliveryDeadline'), 'วันส่งสินค้าต้องไม่ก่อนวันรับออร์เดอร์', 'deliveryDeadlineError');
  return true;
}

function quantityServicePrice(service, calc) {
  const price = Number(service?.price) || 0;
  const serviceUnit = typeof normalizeUnit === 'function' ? normalizeUnit(service?.unit) : String(service?.unit || 'job');
  if (serviceUnit === 'sheet') return price * (Number(calc?.sheets) || 0);
  if (serviceUnit === 'piece') return price * (Number(calc?.Q) || 0);
  return price;
}

function validateCustomServiceRequest(scope = 'main') {
  if (!selectedServiceIds['ui-custom-request'] || customServiceRequest.trim()) return true;
  const input = document.querySelector(`[data-custom-service-request="${scope}"]`) || document.querySelector('[data-custom-service-request]');
  if (input) {
    input.setCustomValidity('กรุณาระบุรายละเอียดที่ต้องการรีเควส');
    input.scrollIntoView({ behavior:'smooth', block:'center' });
    input.reportValidity();
    input.focus({ preventScroll:true });
  }
  return false;
}

function servicePriceLabel(service, calc) {
  return service?.pricePending ? '?' : `฿${money(quantityServicePrice(service, calc))}`;
}

function renderQuantityPriceBreakdown(calc) {
  if (!calc) return;
  $('newSheetSummary').textContent = `${Number(calc.sheets || 0).toLocaleString('th-TH')} แผ่น`;
  $('newPieceSummary').textContent = `${Number(calc.Q || 0).toLocaleString('th-TH')} ชิ้น`;
  const selectedServices = Array.isArray(calc.services) ? calc.services : [];
  $('newServicePriceList').innerHTML = selectedServices.length
    ? selectedServices.map(service => `<div><span>${flowEscape(service.name || 'บริการเพิ่มเติม')}</span><strong>${servicePriceLabel(service, calc)}</strong></div>`).join('')
    : '<div><span>ไม่มีบริการเพิ่มเติม</span><strong>฿0.00</strong></div>';
  $('newTotalPriceSummary').textContent = `฿${money(Number(calc.sale) || 0)}`;
}

function requestVariantQuantityConfirmation() {
  const variants = readVariantInputs();
  const newQuantity = variants.reduce((sum, variant) => sum + variant.quantity, 0);
  const oldQuantity = Number($('qty')?.value) || 0;
  if (!newQuantity || newQuantity === oldQuantity) return false;
  const oldPrice = Number(lastCalc?.sale) || 0;
  $('qty').value = newQuantity;
  $('qty').dispatchEvent(new Event('change', { bubbles: true }));
  calculate();
  pendingVariantQuantityChange = { oldQuantity, newQuantity, oldPrice, newPrice: Number(lastCalc?.sale) || 0 };
  $('oldQuantitySummary').textContent = `${oldQuantity.toLocaleString('th-TH')} ชิ้น`;
  $('oldPriceSummary').textContent = `฿${money(oldPrice)}`;
  $('newQuantitySummary').textContent = `${newQuantity.toLocaleString('th-TH')} ชิ้น`;
  $('newPriceSummary').textContent = `฿${money(pendingVariantQuantityChange.newPrice)}`;
  renderQuantityPriceBreakdown(lastCalc);
  $('quantityChangeModal').classList.add('open');
  $('quantityChangeModal').setAttribute('aria-hidden', 'false');
  return true;
}

function closeVariantQuantityConfirmation(keepNewQuantity) {
  const change = pendingVariantQuantityChange;
  if (!change) return;
  if (!keepNewQuantity) {
    $('qty').value = change.oldQuantity;
    calculate();
    requestAnimationFrame(() => document.querySelector('#jobVariants [data-variant-quantity]')?.focus());
  }
  $('quantityChangeModal').classList.remove('open');
  $('quantityChangeModal').setAttribute('aria-hidden', 'true');
  pendingVariantQuantityChange = null;
  if (keepNewQuantity && renderBriefReview()) showAppView('review');
}

function renderBriefReview(options = {}) {
  if (!lastCalc) return false;
  if (!options.skipValidation && !validateBriefForm()) return false;

  const variants = getJobVariants();
  const services = (lastCalc.services || []).map(service => service.name).filter(Boolean).join(' • ') || 'ไม่มีบริการเพิ่มเติม';
  const link = $('briefFileLink').value.trim();
  const note = $('graphicBriefDescription').value.trim() || 'ไม่มีคำอธิบายเพิ่ม';
  $('briefReviewContent').innerHTML = `
    <div class="brief-review-head"><h2>■ iPrint Brief — ${flowEscape(Number(lastCalc.W).toLocaleString('th-TH'))}×${flowEscape(Number(lastCalc.H).toLocaleString('th-TH'))} cm</h2><small>Preview</small></div>
    <div class="brief-review-name"><strong>ชื่องาน :</strong> ${flowEscape($('jobName').value.trim())}</div>
    <div class="brief-review-variants"><strong>จำนวนแบบ : ${variants.length} แบบ</strong>${variants.map((variant, index) => `<div class="brief-review-variant"><b>แบบที่ ${index + 1}</b><span>${flowEscape(variant.name || '-')}</span><strong>${variant.quantity.toLocaleString('th-TH')} ชิ้น</strong></div>`).join('')}</div>
    <div class="brief-review-metrics"><div><span>ขนาด / จำนวน</span><strong>${flowEscape(lastCalc.W)}×${flowEscape(lastCalc.H)} cm (${Number(lastCalc.Q).toLocaleString('th-TH')} ชิ้น)</strong></div><div><span>การจัดวางชิ้นงาน</span><strong>${lastCalc.b.yield} ชิ้น/แผ่น (${lastCalc.sheets} แผ่น)</strong></div><div><span>วัสดุ / การผลิต</span><strong>${flowEscape(lastCalc.material?.name || lastCalc.paper?.name || '-')}</strong></div><div><span>กำหนดส่งงาน</span><strong>${flowEscape(formatGregorianDate($('deliveryDeadline').value))}</strong></div></div>
    <div class="brief-review-sections"><section class="brief-review-section brief-review-services"><strong>บริการที่เลือก</strong><p>${flowEscape(services)}</p></section><section class="brief-review-section brief-review-technique"><strong>อธิบายเพิ่มเติม</strong><p>${flowEscape(note)}</p></section></div>
    <div class="brief-review-layout preview-gallery">${previewGalleryMarkup()}</div>
    <div class="artwork-summary-slot brief-review-artwork-summary" data-artwork-summary data-artwork-summary-readonly></div>
    ${link ? `<div class="brief-review-note"><strong>ลิงก์ไฟล์ต้นฉบับ</strong><br>${flowEscape(link)}</div>` : ''}`;
  if (typeof renderArtworkSummaries === 'function') renderArtworkSummaries();
  return true;
}

function showOrderSuccess(remote, order) {
  const modal = $('orderSuccessModal');
  const orderId = order?.quoteNo || String(remote?.id || '').slice(0, 12) || '-';
  $('successOrderId').textContent = `Order: ${orderId}`;
  $('successOrderSummary').textContent = `สร้างแล้ว ${Number(remote?.itemIds?.length || order?.orderItems?.length || 0).toLocaleString('th-TH')} รายการ และส่ง Brief ให้กราฟิกแล้ว`;
  modal.classList.add('open');
  modal.setAttribute('aria-hidden', 'false');
}

function closeOrderSuccess() {
  $('orderSuccessModal').classList.remove('open');
  $('orderSuccessModal').setAttribute('aria-hidden', 'true');
}

function prepareNewPrintItem() {
  editingCartItemId = '';
  customServiceRequest = '';
  delete selectedServiceIds['ui-custom-request'];
  quickBriefMode = false;
  setJobType('', { preserveName: true });
  setJobNickname('', { preserveName: true });
  if ($('jobName')) $('jobName').value = '';
  if ($('briefFileLink')) { $('briefFileLink').value = ''; delete $('briefFileLink').dataset.provider; }
  if ($('graphicBriefDescription')) $('graphicBriefDescription').value = '';
  if ($('briefDeadline')) $('briefDeadline').value = '';
  if ($('deliveryDeadline')) $('deliveryDeadline').value = '';
  ['jobNickname','quizDeliveryDeadline'].forEach(id => { if ($(id)) $(id).value = ''; });
  document.querySelectorAll('[data-quiz-date-for]').forEach(input => { input.value = ''; });
  document.querySelectorAll('[data-date-for]').forEach(input => { input.value = ''; });
  setJobVariants([{ name: '', quantity: Number($('qty')?.value) || 0 }]);
  if (typeof clearTemporaryImages === 'function') clearTemporaryImages();
}

function bindFlow() {
  setJobVariants([{ name: '', quantity: Number($('qty').value) || 500 }]);
  showAppView('home', { instant: true });
  $('startPrintOrder').addEventListener('click', () => { quickBriefMode = false; showJobSetupQuestion(1); showAppView('jobSetup'); });
  $('startQuickBrief')?.addEventListener('click', startQuickBrief);
  $('quickBriefContinue')?.addEventListener('click', continueQuickBrief);
  [['quickW', 'w'], ['quickH', 'h'], ['quickQty', 'qty']].forEach(([quickId, sourceId]) => {
    $(quickId)?.addEventListener('input', event => {
      $(sourceId).value = event.target.value;
      calculate();
    });
  });
  $('quickSheet')?.addEventListener('change', event => {
    selectedSheet = event.target.value;
    $('sheet').value = selectedSheet;
    saveState();
    calculate();
  });
  $('quickMaterialSelect')?.addEventListener('change', event => {
    selectedMaterialId = event.target.value;
    $('materialSelect').value = selectedMaterialId;
    saveState();
    renderMaterials();
    calculate();
  });
  $('quickJobName')?.addEventListener('input', event => { $('jobName').value = event.target.value; });
  $('quickQty')?.addEventListener('change', () => setJobVariants([{ name: $('quickJobName')?.value.trim() || '', quantity: Number($('quickQty')?.value) || 0 }]));
  $('goHome').addEventListener('click', () => showAppView('home'));
  $('headerHome')?.addEventListener('click', () => showAppView('home'));
  $('headerWorkflow')?.addEventListener('click', () => openWorkflow());
  document.querySelectorAll('[data-flow-next]').forEach(button => button.addEventListener('click', () => {
    if (button.dataset.flowNext === 'brief' && !validateCustomServiceRequest('main')) return;
    showAppView(button.dataset.flowNext);
  }));
  document.querySelectorAll('[data-flow-back]').forEach(button => button.addEventListener('click', () => showAppView(button.dataset.flowBack)));
  $('reviewBrief').addEventListener('click', () => {
    if (requestVariantQuantityConfirmation()) return;
    if (renderBriefReview()) showAppView('review');
  });
  $('editVariantQuantity')?.addEventListener('click', () => closeVariantQuantityConfirmation(false));
  $('confirmVariantPrice')?.addEventListener('click', () => closeVariantQuantityConfirmation(true));
  const returnFromReview = () => showAppView(quickBriefMode ? 'quickBrief' : 'brief');
  $('editBrief').addEventListener('click', returnFromReview);
  $('reviewViewBack')?.addEventListener('click', returnFromReview);
  $('editMainArtwork')?.addEventListener('click', () => { showAppView('layout'); requestAnimationFrame(() => $('artworkImage')?.click()); });
  $('addAnotherItem').addEventListener('click', () => { prepareNewPrintItem(); showJobSetupQuestion(1); showAppView('jobSetup'); });
  $('workflowNewOrder').addEventListener('click', () => showAppView('home'));
  $('addJobVariant').addEventListener('click', () => {
    currentJobVariants = readVariantInputs();
    currentJobVariants.push({ id: variantId(), name: '', quantity: 0 });
    renderJobVariants();
    announceUiChange('เพิ่มแบบงานใหม่แล้ว กรุณาระบุชื่อและจำนวน', $('jobVariants')?.lastElementChild);
  });
  document.querySelector('[data-job-quiz-question="1"]')?.addEventListener('click', event => {
    const button = event.target.closest('[data-job-type]');
    if (button) {
      setJobType(button.dataset.jobType);
      const customForm = $('jobTypeOtherForm');
      const isOther = button.dataset.jobType === 'อื่น ๆ';
      if (customForm) customForm.hidden = !isOther;
      if (isOther) {
        requestAnimationFrame(() => $('jobTypeOther')?.focus());
        return;
      }
      showJobSetupQuestion(2);
      announceUiChange('เลือกประเภทงานแล้ว ตั้งชื่องานต่อได้เลย', $('[data-job-quiz-question="2"]'));
    }
  });
  $('jobTypeOtherForm')?.addEventListener('submit', event => {
    event.preventDefault();
    const customType = $('jobTypeOther')?.value.trim();
    if (!customType) return;
    setJobType(customType);
    showJobSetupQuestion(2);
  });
  $('jobSetupToHome')?.addEventListener('click', () => showAppView('home'));
  $('jobSetupBack')?.addEventListener('click', () => showJobSetupQuestion(1));
  $('jobNicknameForm')?.addEventListener('click', event => {
    const suggestion = event.target.closest('[data-job-name-suggestion]');
    if (!suggestion) return;
    const value = randomJobNickname(suggestion.dataset.jobNameSuggestion || '');
    setJobNickname(value);
    document.querySelectorAll('[data-job-name-suggestion]').forEach(button => {
      const selected = button === suggestion;
      button.classList.toggle('is-selected', selected);
      button.setAttribute('aria-pressed', selected ? 'true' : 'false');
    });
    $('jobNickname')?.focus();
    announceUiChange(`สุ่มชื่องาน “${value}” แล้ว`, $('jobNickname'), { scroll: false });
  });
  $('jobNickname')?.addEventListener('input', event => {
    document.querySelectorAll('[data-job-name-suggestion]').forEach(button => {
      const suggestion = String(button.dataset.jobNameSuggestion || '').trim();
      const value = event.target.value.trim();
      const selected = value === suggestion || value.startsWith(`${suggestion} `);
      button.classList.toggle('is-selected', selected);
      button.setAttribute('aria-pressed', selected ? 'true' : 'false');
    });
  });
  $('jobNicknameForm')?.addEventListener('submit', event => { event.preventDefault(); setJobNickname($('jobNickname')?.value || ''); showJobSetupQuestion(3); });
  $('jobDatesBack')?.addEventListener('click', () => showJobSetupQuestion(2));
  $('jobDatesForm')?.addEventListener('submit', event => {
    event.preventDefault();
    const deliveryDate = normalizeFlowDateValue($('quizDeliveryDeadline').value);
    const briefDate = getLocalTodayIso();
    if (!deliveryDate || deliveryDate < briefDate) {
      $('quizDeliveryDeadline').setCustomValidity('วันส่งสินค้าต้องเป็นวันนี้หรือหลังจากวันนี้');
      $('quizDeliveryDeadline').reportValidity();
      return;
    }
    $('quizDeliveryDeadline').setCustomValidity('');
    completeJobSetup();
  });
  $('jobName')?.addEventListener('input', event => {
    if (event.target.value !== event.target.dataset.autoGenerated) delete event.target.dataset.autoGenerated;
  });
  const previewReadMore = [...document.querySelectorAll('.preview-read-more')];
  let previewInfoWasRead = false;
  previewReadMore.forEach(details => details.addEventListener('toggle', () => {
    if (!details.open || previewInfoWasRead) return;
    previewInfoWasRead = true;
    previewReadMore.forEach(item => item.classList.remove('is-unread'));
  }));
  $('jobVariants').addEventListener('input', () => validateJobVariants(false));
  $('jobVariants').addEventListener('click', event => {
    const button = event.target.closest('[data-remove-variant]');
    if (!button || currentJobVariants.length <= 1) return;
    const row = button.closest('.job-variant');
    currentJobVariants = readVariantInputs().filter(variant => variant.id !== row?.dataset.variantId);
    renderJobVariants();
    validateJobVariants(true);
  });
  $('qty').addEventListener('change', () => {
    const variants = readVariantInputs();
    if (variants.length === 1) {
      variants[0].quantity = Number($('qty').value) || 0;
      setJobVariants(variants);
    }
  });
  document.querySelectorAll('[data-service-option]').forEach(button => button.addEventListener('click', () => {
    if (button.getAttribute('aria-disabled') === 'true') return;
    selectedHomeService = button.dataset.serviceOption || 'laser';
    document.querySelectorAll('[data-service-option]').forEach(option => {
      const selected = option === button;
      option.classList.toggle('is-selected', selected);
      option.setAttribute('aria-pressed', selected ? 'true' : 'false');
      const badge = option.querySelector('.service-state');
      if (badge && !option.classList.contains('is-coming-soon')) badge.textContent = selected ? 'Selected' : 'เลือก';
    });
    const art = button.querySelector('.service-art');
    $('serviceHero').dataset.selectedService = selectedHomeService;
    $('serviceHero').setAttribute('aria-label', `กำลังเลือกบริการ ${button.dataset.title || ''}`);
    const heroArt = $('serviceHero').querySelector('.hero-service-art');
    heroArt.className = art?.className + ' hero-service-art';
    heroArt.replaceChildren(...[...art?.children || []].map(child => child.cloneNode(true)));
    $('serviceHeroTitle').textContent = button.dataset.title || '';
    $('serviceHeroDescription').textContent = button.dataset.description || '';
  }));
  document.querySelectorAll('[data-file-provider]').forEach(button => button.addEventListener('click', event => {
    document.querySelectorAll('[data-file-provider]').forEach(option => option.classList.toggle('is-selected', option === button));
    $('briefFileLink').dataset.provider = button.dataset.fileProvider;
    if ($('cloudLinkNote')) $('cloudLinkNote').textContent = `เปิด ${button.textContent.replace('↗', '').trim()} ในแท็บใหม่แล้ว • สร้าง Share link จากไฟล์ จากนั้นกลับมาวางลิงก์ที่นี่`;
  }));
  ['quizDeliveryDeadline'].forEach(id => {
    const datePicker = document.querySelector(`[data-quiz-date-for="${id}"]`);
    const openDatePicker = event => {
      if (event?.type === 'keydown' && !['Enter', ' ', 'ArrowDown'].includes(event.key)) return;
      event?.preventDefault();
      try { datePicker?.showPicker(); } catch { datePicker?.click(); }
    };
    $(id)?.addEventListener('click', openDatePicker);
    $(id)?.addEventListener('keydown', openDatePicker);
    datePicker?.addEventListener('change', event => {
      setQuizDateValue(id, event.target.value);
      $(id)?.setCustomValidity('');
      $(id)?.dispatchEvent(new Event('change', { bubbles: true }));
    });
  });
  [['w', 'wSlider'], ['h', 'hSlider']].forEach(([inputId, sliderId]) => {
    const input = $(inputId);
    const slider = $(sliderId);
    if (!input || !slider) return;
    const syncSlider = () => { slider.value = input.value; };
    input.addEventListener('input', syncSlider);
    slider.addEventListener('input', () => {
      input.value = slider.value;
      input.dispatchEvent(new Event('input', { bubbles: true }));
      input.dispatchEvent(new Event('change', { bubbles: true }));
    });
  });
  ['briefDeadline', 'deliveryDeadline', 'quickDeliveryDeadline'].forEach(id => {
    const datePicker = document.querySelector(`[data-date-for="${id}"]`);
    const openDatePicker = event => {
      if (event?.type === 'keydown' && !['Enter', ' ', 'ArrowDown'].includes(event.key)) return;
      event?.preventDefault();
      try { datePicker?.showPicker(); } catch { datePicker?.click(); }
    };
    $(id).addEventListener('click', openDatePicker);
    $(id).addEventListener('keydown', openDatePicker);
    $(id).addEventListener('input', event => {
      const digits = event.target.value.replace(/\D/g, '').slice(0, 8);
      event.target.value = [digits.slice(0, 2), digits.slice(2, 4), digits.slice(4, 8)].filter(Boolean).join('/');
      event.target.classList.remove('is-invalid');
      const error = $(`${id}Error`);
      if (error) error.textContent = '';
    });
    $(id).addEventListener('blur', event => {
      event.target.value = formatFlowDateInput(event.target.value);
      if (datePicker) datePicker.value = normalizeFlowDateValue(event.target.value);
    });
    datePicker?.addEventListener('change', event => {
      $(id).value = formatFlowDateInput(event.target.value);
      $(id).classList.remove('is-invalid');
      const error = $(`${id}Error`);
      if (error) error.textContent = '';
      $(id).dispatchEvent(new Event('change', { bubbles: true }));
    });
  });
  $('startNewOrder').addEventListener('click', () => { closeOrderSuccess(); prepareNewPrintItem(); showAppView('home'); });
  $('viewOrderStatus').addEventListener('click', () => { closeOrderSuccess(); openWorkflow(); });
  $('openMaterialsServices').addEventListener('click', () => {
    if (typeof hasSelectedPrintService === 'function' && !hasSelectedPrintService()) return;
    if (typeof closeSide === 'function') closeSide();
    showAppView('cost');
  });
  $('costPreviewModeToggle')?.addEventListener('click', event => {
    const button = event.target.closest('[data-cost-preview-mode]');
    if (button) setCostPreviewMode(button.dataset.costPreviewMode);
  });
  $('rotateCostPiecePaper')?.addEventListener('click', rotateCostPiecePaper);
  document.addEventListener('click', event => {
    const control = event.target.closest('[data-preview-carousel-action], [data-preview-carousel-index]');
    if (!control) return;
    const carousel = control.closest('[data-preview-carousel]');
    if (!carousel) return;
    if (control.dataset.previewCarouselIndex !== undefined) {
      syncPreviewCarousel(carousel, Number(control.dataset.previewCarouselIndex));
      return;
    }
    const current = Number(carousel.dataset.previewIndex) || 0;
    syncPreviewCarousel(carousel, current + (control.dataset.previewCarouselAction === 'prev' ? -1 : 1));
  });
  window.addEventListener('iprint:calculated', syncFlowSummary);
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bindFlow, { once: true });
else bindFlow();

window.showAppView = showAppView;
window.syncFlowSummary = syncFlowSummary;
window.getJobVariants = getJobVariants;
window.setJobVariants = setJobVariants;
window.validateJobVariants = validateJobVariants;
window.getSelectedPrintSide = () => {
  const selected = services.filter(service => selectedServiceIds[String(service.id)]).map(service => String(service.name || '').toLowerCase());
  if (selected.some(name => /2\s*หน้า|สองหน้า|double/.test(name))) return 'double';
  if (selected.some(name => /หน้าเดียว|single/.test(name))) return 'single';
  return 'unspecified';
};
window.getSelectedHomeService = () => selectedHomeService;
window.getLockedCuttingMode = () => lockedCuttingMode;
window.normalizeFlowDateValue = normalizeFlowDateValue;
window.formatFlowDateInput = formatFlowDateInput;
window.showOrderSuccess = showOrderSuccess;
window.renderBriefReview = renderBriefReview;
window.setJobType = setJobType;
window.getSelectedJobType = getSelectedJobType;
window.setJobNickname = setJobNickname;
window.isJobNameSuggestionVisible = isJobNameSuggestionVisible;
window.randomJobNickname = randomJobNickname;
window.previewGalleryMarkup = previewGalleryMarkup;
window.setCostPreviewMode = setCostPreviewMode;
window.getCostPreviewMode = getCostPreviewMode;
window.rotateCostPiecePaper = rotateCostPiecePaper;
window.getCostPiecePaperRotation = getCostPiecePaperRotation;
